export const WHATSAPP_EVENTS = {
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',

  INSTANCE_CREATED: 'INSTANCE_CREATED',
  INSTANCE_CONNECTED: 'INSTANCE_CONNECTED',
  INSTANCE_DISCONNECTED: 'INSTANCE_DISCONNECTED',

  QR_UPDATED: 'QR_UPDATED',
}
