const fs = require('fs');
let code = fs.readFileSync('components/FinanceDashboard.tsx', 'utf8');

const startStr = 'const sendWhatsApp = (name: string) => {';
let startIdx = code.indexOf(startStr);
if (startIdx !== -1) {
  let endIdx = code.indexOf('\n  };', startIdx) + 5;
  const newFunc = Buffer.from('Y29uc3Qgc2VuZFdoYXRzQXBwID0gYXN5bmMgKGF0aGxldGU6IGFueSkgPT4gewogICAgY29uc3QgZGVmYXVsdEFtb3VudCA9IDE1MC4wMDsKICAgIGNvbnN0IG1lc3NhZ2UgPSBgT2zDoSwgJHthdGhsZXRlLm5hbWV9ISBOb3RhbW9zIHF1ZSBhIHN1YSBtZW5zYWxpZGFkZSBkZXN0ZSBtw6pzICgke2N1cnJlbnRNb250aERhdGUudG9Mb2NhbGVEYXRlU3RyaW5nKCdwdC1CUicsIHsgbW9udGg6ICdsb25nJywgeWVhcjogJ251bWVyaWMnIH0pfSkgZW5jb250cmEtc2UgcGVuZGVudGUuIFZhbG9yIHN1Z2VyaWRvOiBSJCAke2RlZmF1bHRBbW91bnR9LiBDaGF2ZSBQSVg6IG5vc3NvZW1haWxAZ21haWwuY29tYDsKCiAgICBpZiAoIWF0aGxldGUucGhvbmUpIHsKICAgICAgYWxlcnQoYE8gYXRsZXRhICR7YXRobGV0ZS5uYW1lfSBuw6NvIHBvc3N1aSB0ZWxlZm9uZSBjYWRhc3RyYWRvLmApOwogICAgICByZXR1cm47CiAgICB9CgogICAgY29uc3QgY2xlYW5QaG9uZSA9IGF0aGxldGUucGhvbmUucmVwbGFjZSgvXEQvZywgJycpOwogICAgaWYgKGNsZWFuUGhvbmUubGVuZ3RoIDwgMTApIHsKICAgICAgYWxlcnQoYE8gdGVsZWZvbmUgY2FkYXN0cmFkbyBwYXJhICR7YXRobGV0ZS5uYW1lfSBwYXJlY2UgaW52w6FsaWRvLmApOwogICAgICByZXR1cm47CiAgICB9CgogICAgdHJ5IHsKICAgICAgY29uc3QgcmVzID0gYXdhaXQgZmV0Y2goJy9hcGkvd2hhdHNhcHAvc2VuZCcsIHsKICAgICAgICBtZXRob2Q6ICdQT1NUJywKICAgICAgICBoZWFkZXJzOiB7ICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicgfSwKICAgICAgICBib2R5OiBKU09OLnN0cmluZ2lmeSh7IHBob25lOiBjbGVhblBob25lLCBtZXNzYWdlIH0pCiAgICAgIH0pOwogICAgICBjb25zdCBkYXRhID0gYXdhaXQgcmVzLmpzb24oKTsKICAgICAgaWYgKCFyZXMub2spIHsKICAgICAgICB0aHJvdyBuZXcgRXJyb3IoZGF0YS5lcnJvciB8fCAnRXJybyBhbyBlbnZpYXIgV2hhdHNBcHAgcGVsYSBhdXRvbWHDp8OjbC4nKTsKICAgICAgfQogICAgICBhbGVydChgTWVuc2FnZW0gZW52aWFkYSBwYXJhICR7YXRobGV0ZS5uYW1lfSBjb20gc3VjZXNzbyB2aWEgYXV0b21hw6fDo28hYCk7CiAgICB9IGNhdGNoIChlcnI6IGFueSkgewogICAgICBjb25zb2xlLndhcm4oJ0Vycm8gYW8gZW52aWFyIHZpYSBhdXRvbWHDp8OjbywgY2FpbmRvIHBhcmEgbyBXaGF0c0FwcCBXZWIuJywgZXJyKTsKICAgICAgY29uc3QgZW5jb2RlZE1lc3NhZ2UgPSBlbmNvZGVVUklDb21wb25lbnQobWVzc2FnZSk7CiAgICAgIGNvbnN0IHdoYXRzYXBwVXJsID0gYGh0dHBzOi8vd2EubWUvJHtjbGVhblBob25lLnN0YXJ0c1dpdGgoJzU1JykgPyBjbGVhblBob25lIDogJzU1JyArIGNsZWFuUGhvbmV9P3RleHQ9JHtlbmNvZGVkTWVzc2FnZX1gOwogICAgICB3aW5kb3cub3Blbih3aGF0c2FwcFVybCwgJ19ibGFuaycpOwogICAgfQogIH07', 'base64').toString('utf8');
  code = code.substring(0, startIdx) + newFunc + code.substring(endIdx);
  code = code.replace(
    'onClick={() => sendWhatsApp(a.name)}',
    'onClick={() => sendWhatsApp(a)}'
  );
  fs.writeFileSync('components/FinanceDashboard.tsx', code);
  console.log('FinanceDashboard patched successfully');
} else {
  console.log('sendWhatsApp not found in FinanceDashboard');
}
